urls.py
from django.conf.urls.defaults import *
from deck.views import *
from game.views import *
import os.path
from django.contrib import admin

site_media = os.path.join(
	os.path.dirname(__file__), 'site_media'
)

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

admin.autodiscover()

urlpatterns = patterns('',
	(r'^$', main_page),
	(r'^user/(\w+)/$', user_page),
	(r'^login/$', 'django.contrib.auth.views.login'),
	(r'^logout/$', logout_page),
	(r'^deck_builder/(\d+)/$', deck_builder),
	(r'^deck_builder/(\d+)/add/(\d+)/$', add_to_deck),
	(r'^deck_builder/(\d+)/del/(\d+)/$', delete_from_deck),
	(r'^deck_builder/$', deck_select),
	(r'^herebedragons/$', register_page),
	(r'^goaway/', include(admin.site.urls)),
	(r'^accept/(\d+)/(\d+)/$', accept_proposal),
	(r'^decline/(\d+)/$', decline_proposal),
	(r'^propose/$', propose),
	(r'^games/$', games_page),
	(r'^game/(\d+)/$', game_page),
	(r'^game/(\d+)/draw/$', draw),
	(r'^game/(\d+)/sync$', 'game.views.sync'),
	(r'^game/move/(\d+)/x(\d+)/y(\d+)/z(\d+)/$', move),
	(r'^game/changeArea/(\d+)/(\w)/$', changeArea),
#	(r'^test/$', 'chat.views.test'),
	(r'^chat/send/$', 'chat.views.send'),
 	(r'^chat/receive/$', 'chat.views.receive'),
 	(r'^chat/sync/$', 'chat.views.sync'),
    	(r'^chat/join/$', 'chat.views.join'),
	(r'^chat/leave/$', 'chat.views.leave'),
	(r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
		{'document_root': site_media }), 
   # Example:
    # (r'^django_test/', include('django_test.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    #(r'^admin/', include(admin.site.urls)),
)

deck/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Card(models.Model):
	name = models.CharField(max_length=50)
	cost = models.IntegerField()
	race = models.CharField(max_length=15)
	num = models.IntegerField()
	def __str__(self):
		return self.name
	
class Decks(models.Model):
	name = models.CharField(max_length=50)
	owner = models.ForeignKey(User)	
	def __str__(self):
		return self.name

class Deck(models.Model):
	cardID = models.ForeignKey(Card)
	deckID = models.ForeignKey(Decks)	
	qty = models.IntegerField()
	def __str__(self):
		return "%s: %s: %d" % (self.deckID.name, self.cardID.name, self.qty)

game/models.py
from django.db import models
from django.contrib.auth.models import User
from deck.models import *

class Game(models.Model):
	player1 = models.ForeignKey(User, related_name='player1')
	player2 = models.ForeignKey(User, related_name='player2')
	p1Deck = models.ForeignKey(Decks, related_name='p1Deck')
	p2Deck = models.ForeignKey(Decks, related_name='p2Deck')
	lastAdd = models.PositiveIntegerField()
	def __str__(self):
		return self.player1.username + " v " + self.player2.username

class Proposal(models.Model):
	proposer = models.ForeignKey(User, related_name='proposer')
	recipient = models.ForeignKey(User, related_name='recipient')
	proposerDeck = models.ForeignKey(Decks)
	message = models.CharField(max_length=255, blank=True, null=True)
	time = models.DateTimeField(auto_now=True)
	def __str__(self):
		return self.proposer.username + ' v ' + self.recipient.username

CARD_LOCATIONS = (
	('d', 'deck'),
	('h', 'hand'),
	('t', 'table'),
	('s', 'discard')
)

class GameCard(models.Model):
	''' A card in a game '''
	game = models.ForeignKey(Game)
	owner = models.ForeignKey(User)
	location = models.CharField(max_length=1, choices=CARD_LOCATIONS)
	card = models.ForeignKey(Card)
	xLoc = models.PositiveSmallIntegerField()
	yLoc = models.PositiveSmallIntegerField()
	zLoc = models.PositiveSmallIntegerField()
	def __str__(self):
		return "%s %s:%d,%d,%d" % (self.owner.username, self.card.name, self.xLoc, self.yLoc, self.zLoc)

TOKEN_COLOR = (
	('r', 'red'),
	('b', 'black')
)

class Token(models.Model):
	game = models.ForeignKey(Game)
	color = models.CharField(max_length=1, choices=TOKEN_COLOR)
	xLoc = models.PositiveSmallIntegerField()
	yLoc = models.PositiveSmallIntegerField()
	qty = models.PositiveSmallIntegerField()
	def __str__(self):
		return "%s %s" % (self.game, self.color)

deck/forms.py
from django import forms
import re
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist

class NewDeckForm(forms.Form):
	deckName = forms.CharField(
		label='Deck Name',
		max_length=50,
		widget=forms.TextInput(attrs={'size':50, ' max_length':50})
	)

class AllUserDropdownForm(forms.Form):
	usersDrop = forms.ModelChoiceField(queryset=User.objects.all())

class RegistrationForm(forms.Form):
	username = forms.CharField(label='Username', max_length=30)
	email = forms.EmailField(label='Email')
	password1 = forms.CharField(
		label='Password',
		widget=forms.PasswordInput()
	)
	password2 = forms.CharField(
		label='Password (Again)',
		widget=forms.PasswordInput()
	)

	def clean_password2(self):
		if 'password1' in self.cleaned_data:
			password1 = self.cleaned_data['password1']
			password2 = self.cleaned_data['password2']
			if password1 == password2:
				return password2
		raise forms.ValidationError('Passwords do not match...')

	def clean_username(self):
		username = self.cleaned_data['username']
		if not re.search(r'^\w+$', username):
			raise forms.ValidationError('Stupid username...')
		try:
			User.objects.get(username=username)
		except ObjectDoesNotExist:
			return username
		raise forms.ValidationError('Username taken.')

chat/views.py
from datetime import datetime

from django.http import HttpResponse, Http404
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from django.contrib.auth.models import User 
from django.views.decorators.csrf import csrf_exempt
from models import Room, Message

@login_required
@csrf_exempt
def send(request):
    '''
    Expects the following POST parameters:
    chat_room_id
    message
    '''
    p = request.POST
    r = Room.objects.get(id=int(p['chat_room_id']))
    r.say(request.user, p['message'])
    return HttpResponse('')

@login_required
@csrf_exempt
def sync(request):
    '''Return last message id

    EXPECTS the following POST parameters:
    id
    '''
    if request.method != 'POST':
        raise Http404
    post = request.POST

    if not post.get('id', None):
        raise Http404

    r = Room.objects.get(id=post['id'])
    
    lmid = r.last_message_id()    
    
    return HttpResponse(jsonify({'last_message_id':lmid}))

@login_required
@csrf_exempt
def receive(request):
    '''
    Returned serialized data
    
    EXPECTS the following POST parameters:
    id
    offset
    
    This could be useful:
    @see: http://www.djangosnippets.org/snippets/622/
    '''
    if request.method != 'POST':
        raise Http404
    post = request.POST

    if not post.get('id', None) or not post.get('offset', None):
        raise Http404
    
    try:
        room_id = int(post['id'])
    except:
        raise Http404

    try:
        offset = int(post['offset'])
    except:
        offset = 0
    
    r = Room.objects.get(id=room_id)

    m = r.messages(offset)

    
    return HttpResponse(jsonify(m, ['id','author','message','type']))


@login_required
@csrf_exempt
def join(request):
    '''
    Expects the following POST parameters:
    chat_room_id
    message
    '''
    p = request.POST
    r = Room.objects.get(id=int(p['chat_room_id']))
    r.join(request.user)
    return HttpResponse('')


@login_required
@csrf_exempt
def leave(request):
    '''
    Expects the following POST parameters:
    chat_room_id
    message
    '''
    p = request.POST
    r = Room.objects.get(id=int(p['chat_room_id']))
    r.leave(request.user)
    return HttpResponse('')


@login_required
@csrf_exempt
def test(request):
    '''Test the chat application'''
    
    u = User.objects.get(id=1) # always attach to first user id
    r = Room.objects.get_or_create(u)

    return render_to_response('chat.html', {'js': ['/media/js/mg/chat.js'], 'chat_id':r.pk}, context_instance=RequestContext(request))


def jsonify(object, fields=None, to_dict=False):
    '''Simple convert model to json'''
    try:
        import json
    except:
        import django.utils.simplejson as json
 
    out = []
    if type(object) not in [dict,list,tuple] :
        for i in object:
            tmp = {}
            if fields:
                for field in fields:
                    tmp[field] = unicode(i.__getattribute__(field))
            else:
                for attr, value in i.__dict__.iteritems():
                    tmp[attr] = value
            out.append(tmp)
    else:
        out = object
    if to_dict:
        return out
    else:
        return json.dumps(out)

deck/views.py
# Create your views here.
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import Context, RequestContext
from django.template.loader import get_template
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import logout
from django.shortcuts import render_to_response
from deck.forms import *
from deck.models import *
from chat.models import *
from game.models import *
from django import forms

def main_page(request):
	u = User.objects.get(id=1)
	r = Room.objects.get_or_create(u)
	return render_to_response(
		'news.html',
		RequestContext(request, { "chat_id":r.pk }),
	)

def games_page(request):
	games = Game.objects.filter(player1=request.user)
	games2 = Game.objects.filter(player2=request.user)
	incomingProposals = Proposal.objects.filter(recipient=request.user)
	outgoingProposals = Proposal.objects.filter(proposer=request.user)
	u = User.objects.get(id=1)
	r = Room.objects.get_or_create(u)
	userDrop = AllUserDropdownForm()
	decks = Decks.objects.filter(owner=request.user)
	return render_to_response('games.html',
		RequestContext(request, { "chat_id":r.pk, "games":games, 'games2':games2, 'incomingProposals':incomingProposals, 'outgoingProposals':outgoingProposals, 'userDrop':userDrop, 'decks':decks }),
	)

def accept_proposal(request, proposalID, deckID):
	deck = Decks.objects.get(id=deckID)
	proposal = Proposal.objects.get(id=proposalID)
	game = Game(
		player1 = proposal.proposer,
		player2 = proposal.recipient,
		p1Deck = proposal.proposerDeck,
		p2Deck = deck,
		lastAdd = 0)
	game.save()
	setup(game)
	proposal.delete()	
	return HttpResponseRedirect("/game/%d" % game.id)

def setup(game):
	for card in Deck.objects.filter(deckID=game.p1Deck):
		GameCard(
			game = game,
			owner = game.player1,
			location = 'd',
			card = card.cardID,
			xLoc = 0,
			yLoc = 0, 
			zLoc = 1
		).save()
	for card in Deck.objects.filter(deckID=game.p2Deck):
		GameCard(
			game = game,
			owner = game.player2,
			location = 'd',
			card = card.cardID,
			xLoc = 0,
			yLoc = 0, 
			zLoc = 1
		).save()


def decline_proposal(request, proposalID):
	Proposal.objects.get(id=proposalID).delete()
	return HttpResponseRedirect('/games/')

@login_required
@csrf_exempt
def propose(request):
	p = request.POST
	proposer = request.user
	deck = Decks.objects.get(id=int(p['deck']))
	message = p['message']
	recipient = User.objects.get(id=int(p['recipient']))
	proposal = Proposal(
		proposer = proposer,
		proposerDeck = deck,
		message = message,
		recipient = recipient	
	)
	proposal.save()
	return HttpResponseRedirect('/games/')

def add_to_deck(request, deckID, cardID):
#first arg will be deckID, second arg will be cardiid
	owner = Decks.objects.get(id=deckID).owner
	if request.user != owner:
		return HttpResponseRedirect('/deck_builder/')
	deck = Decks.objects.get(id=deckID)
	card = Card.objects.get(id=cardID)	
	deckCard = Deck.objects.filter(deckID=deck, cardID=card)
	if len(deckCard) == 1:
		deckCard[0].qty += 1
		deckCard[0].save()
	else:
		Deck.objects.get_or_create(deckID=deck, cardID=card, qty=1)
	return HttpResponseRedirect('/deck_builder/%s/' % deckID)

def delete_from_deck(request, deckID, cardID):
#first arg will be deckID, second arg will be cardiid
	owner = Decks.objects.get(id=deckID).owner
	if request.user != owner:
		return HttpResponseRedirect('/deck_builder/')
	deck = Decks.objects.get(id=deckID)
	card = Card.objects.get(id=cardID)	
	deckCard = Deck.objects.filter(deckID=deck, cardID=card)
	if len(deckCard) == 1:
		if deckCard[0].qty == 1:
			deckCard[0].delete()
		else:
			deckCard[0].qty -= 1
			deckCard[0].save()
	return HttpResponseRedirect('/deck_builder/%s/' % deckID)

def deck_builder(request, deckID):
	try:
		deck = Decks.objects.get(id=deckID)
	except:
		raise Http404('Deck not found, try making it first.')
	deckCards = Deck.objects.filter(deckID=deck)
	cards = Card.objects.all()
	return render_to_response(
		'deck_builder.html',
		RequestContext(request, { 'cards': cards, 'deck': deck, 'deckCards': deckCards })
	)

def deck_select(request):
	if request.method == 'POST':
		form = NewDeckForm(request.POST)
		if form.is_valid():
			#add deck
			deckName = form.cleaned_data['deckName']
			if len(deckName) < 50 and len(deckName) > 0:
				deck, made = Decks.objects.get_or_create(
					owner = request.user,
					name = deckName
				)
				return HttpResponseRedirect('/deck_builder/%s/' % deck.id)
			else:
				return HttpResponseRedirect('/deck_builder/')
		return HttpResponseRedirect('/deck_builder/')
	else:
		form = NewDeckForm()
		decks = Decks.objects.filter(owner=request.user)
		return render_to_response(
			'deck_select.html',
			RequestContext(request, { 'form': form, 'decks': decks })
		)
					
def user_page(request, username):
	try:
		user = User.objects.get(username=username)
	except:
		raise Http404('U Dumb')
	books = user.bookmark_set.all()
	template = get_template('user_page.html')
	variables = RequestContext(request, {
		'username': username,
		'bookmarks': books
	})
	return render_to_response('user_page.html', variables)

def logout_page(request):
	logout(request)
	return HttpResponseRedirect('/')

def register_page(request):
	if request.method == 'POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			user = User.objects.create_user(
				username = form.cleaned_data['username'],
				password = form.cleaned_data['password1'],
				email = form.cleaned_data['email']
			)
			return HttpResponseRedirect('/')
	else:
		form = RegistrationForm()
	variables = RequestContext(request, {
		'form': form
	})
	return render_to_response(
		'registration/register.html',
		variables
	)

game/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import Context, RequestContext
from django.shortcuts import render_to_response
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
import django.utils.simplejson as json
import time, random
from deck.models import *
from game.models import *
from chat.models import *

def game_page(request, id):
	try:
		game = Game.objects.get(id=id)
		r = Room.objects.get_or_create(game)
		playArea = GameCard.objects.filter(game=game, location='t')
		hand = GameCard.objects.filter(game=game, location='h', owner=request.user)
		deckCount = len(GameCard.objects.filter(game=game, owner=request.user, location='d'))
		return render_to_response(
			'game.html',
			RequestContext(request, {"cards": playArea, "hand":hand, "chat_id":r.pk, "p1":game.player1, "p2":game.player2, "deckCount":deckCount })
		)
	except:
		raise Http404('Whoops')

@login_required
@csrf_exempt
def move(request, cID, x, y, z):
	try:
		card = GameCard.objects.get(id=cID)
		card.xLoc = x
		card.yLoc = y
		card.zLoc = z
		card.save()
		return HttpResponse('')
	except:
		raise Http404('Whoops move')

@login_required
def draw(request, gameID):
	game = Game.objects.get(id=gameID)
	deck = GameCard.objects.filter(game=game, owner=request.user, location='d')
	if( len(deck) > 0):
		draw = deck[random.randint(0, (len(deck) - 1))]
		draw.location = 'h'
		draw.yLoc = 786
		draw.xLoc = 50
		draw.save()
		game.lastAdd = time.time() * 1000
		game.save()
	return HttpResponse('')

@login_required
@csrf_exempt
def changeArea(request, cID, loc):
	try:
		card = GameCard.objects.get(id=cID)
		card.location = loc
		card.save()
		card.game.lastAdd = time.time() * 1000
		card.game.save()
		return HttpResponse('')
	except:
		raise Http404('Whoops changeArea')

@login_required
@csrf_exempt
def sync(request, id):
	try:	
		game = Game.objects.get(id=id)
		out = []
		cards = GameCard.objects.filter(game=game).exclude(location='d')
		for c in cards:
			tmp = {}
			tmp['type'] = 'card'
			tmp['id'] = c.id
			tmp['x'] = c.xLoc
			tmp['y'] = c.yLoc
			tmp['z'] = c.zLoc
			out.append(tmp)
		tokens = Token.objects.filter(game=game)
		for t in tokens:
			tmp = {}
			tmp['type'] = 'token'
			tmp['id'] = t.id
			tmp['x'] = t.xLoc
			tmp['y'] = t.yLoc
			tmp['qty'] = t.qty
			out.append(tmp)
		return HttpResponse(json.dumps([{'lastUpdate': game.lastAdd}, {'data':out}]))

	except:
		raise Http404('Whoops sync')

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
		<title>lotr-online | {% block title %}{% endblock %}</title>
		<script type="text/javascript" src="/site_media/jquery.js"></script>
		<link rel="stylesheet" href="/site_media/style.css" type="text/css" />
		{% block style %}{% endblock %}
		{% block script %}{% endblock %}
	</head>
	<body>
		<div id="nav">
			<a href="/">News</a>
			{% if user.is_authenticated %}
				<a href='/games'>Games</a>
				<a href='/deck_builder'>Decks</a>
				welcome {{ user.username }}
				[<a href="/logout">logout</a>]
			{% else %}
				[<a href="/login">login</a>]
			{% endif %}
		</div>
		<h1>{% block head %}{% endblock %}</h1>
		{% block content %}{% endblock %}
	</body>
</html>

templates/card_table.html
{% for card in cards %}
	<tr>
		<td><a href="/site_media/images/cards/LOTR0{{ card.num }}.jpg">{{ card.name }}</a></td>
		<td>{{ card.cost }}</td>
		<td>{{ card.race }}</td>
		<td><a href="/deck_builder/{{ deck.id }}/add/{{ card.id }}" id="add">[add]</a></td>
	</tr>
{% endfor %}

templates/chat.html
<head>
<script type="text/javascript" src="/site_media/jchat.js"></script>
<link href="/site_media/jchat.css" rel="stylesheet" type="text/css" media="screen,projection" />
</head>
<div id="chat"></div>
<script type="text/javascript">
$(window).ready(function(){
	init_chat({{ chat_id }}, "chat");
})
</script>

templates/deck_builder.html
{% extends "base.html" %}
{% block title %}Deck Builder{% endblock %}
{% block head %}Deck Builder{% endblock %}
{% block style %}
<style type="text/css">
div.AllCards {
	float:left;
	width:450px;
	margin:0;
	padding:1em;
}
div.Deck {
	margin-left:550px;
	padding:1em;
}

/** closure table sorting styles **/
th.header {
	font-weight: bold;
	cursor: pointer
}
th.headerSortDown {
	background-color: #eef;
}
th.headerSortUp {
	background-color: #fee;
}
</style>
{% endblock %}
{% block script %}
<script src="/site_media/imgtooltip.js"></script>
<script src="/site_media/jQuery.uitablefilter.js"></script>
<script src="/site_media/jquery.tablesorter.min.js"></script>
<script>
$(function(){
	$("a[href*='.jpg']").thumbPopup();
});

function deckPop(){
	$("a[href*='.jpg'][id='deckImage']").thumbPopup();
}
</script>
{% endblock %}
{% block content %}
{% if user.username %}
<div class="AllCards">
<b><p>All Cards</p></b>
<table border="0" cellpang="3" id="AllCardsTable" class="tablesorter">
<thead>
	<tr>
		<th>Card Name</th>
		<th>Cost</th>
		<th width=100px>Race</th>
	</tr>
</thead>
<tbody>
{% include "card_table.html" %}
</tbody>
</table>
</div>
<div class="Deck">
<p><b>Deck:</b> {{ deck.name }}</p>
<table border="0" cellpang="3" id="DeckTable">
<thead>
	<tr>
		<th>Card Name</th>
		<th>Cost</th>
		<th>Race</th>
		<th>Qty</th>
	</tr>
</thead>
<tbody id="deckBody">
{% include "deck_table.html" %}
</tbody>
</table>
</div>
<script>
var loading = false; 
function ajax(a){
	a.preventDefault();
	if(!loading){
		loading = true;
		var link = a.currentTarget.href + ' #DeckTable';
		//alert(link);
		$('#DeckTable').load(link, function(){
			loading = false;
			deckPop();
			$('[id$=del]').bind("click", ajax);
		});
	}
}	
$(document).ready(function(){
	$('[id$=add]').bind("click", ajax);
	$('[id$=del]').bind("click", ajax);
	$table = $('#AllCardsTable').tablesorter({widthFixed: true});
	FilterText = "";
	ColumnArray = ["Cost", "Race"];
	for (i=1;i<ColumnArray.length + 1;i++){
		$("#AllCardsTable tbody tr").find("td:eq(" + i + ")").click(function(){
			clickedText = $(this).text();
			FilterText = ((FilterText == clickedText) ? "" : clickedText );
			$.uiTableFilter( $table, FilterText, ColumnArray[i]);
		});
	}
});
</script> 
</script> 
{% else %}
<p>[<a href="/login/">login</a>]</p>
{% endif %}
{% endblock %}

templates/deck_drop.html
<form style=float:left action="">
Deck to use:
<select class="deck_drop" name="deck">
{% for deck in decks %}
<option value="{{ deck.id }}">{{ deck.name }}</option>
{% endfor %}
</select>

</form>

templates/deck_select.html
{% extends "base.html" %}
{% block title %}Decks{% endblock %}
{% block head %}Decks{% endblock %}
{% block content %}
	<b><p>Current Decks</p></b>
	{% for deck in decks %}
	<p><a href="./{{ deck.id }}">{{ deck.name }}</a></p>
	{% endfor %}

	<b><p>Create New Deck</p></b>
	
	<form method="post" action=".">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Create" />
	</form>
{% endblock %}

templates/deck_table.html
{% for dc in deckCards %}
	<tr>
		<td><a href="/site_media/images/cards/LOTR0{{ dc.cardID.num }}.jpg" id="deckImage">{{ dc.cardID.name }}</a></td>
		<td>{{ dc.cardID.cost }}</td>
		<td>{{ dc.cardID.race }}</td>
		<td>{{ dc.qty }}</td>
		<td><a href="/deck_builder/{{ deck.id }}/del/{{ dc.cardID.id }}" id="del">[del]</a></td>
	</tr>
{% endfor %}

templates/games.html
{% extends "base.html" %}
{% block title %}Games{% endblock %}
{% block head %}Games{% endblock %}
{% block style %}
<style type="text/css">
#chat{
	width:85%;
	height:300px;
}
div.proposalDiv {
	margin-left:200px;
}
</style>
{% endblock %}
{% block content %}

{% if user.username %}
<b><p>Incoming Proposals</p></b>
{% for proposal in incomingProposals %}
<div style=float:left>{{proposal}}</div>
<div class="proposalDiv proposal{{proposal.id}}">
{% include "deck_drop.html" %}
<a href="/accept/{{proposal.id}}" id="{{proposal.id}}" class="{{proposal.id}} accept">[accept]</a> <a href="/decline/{{proposal.id}}">[decline]</a>
<p>--{{proposal.message}}</p>
</div>
{% endfor %}

<b><p>Outgoing Proposals</p></b>
{% for proposal in outgoingProposals %}
<p>{{proposal}} <a href="/decline/{{proposal.id}}">[cancel]</a></p>
<p>{{proposal.message}}</p>
{% endfor %}

<b><p>Current Games </p></b>
{% for game in games %}
<p><a href="/game/{{ game.id }}">{{ game }}</a>  --  {{game.p1Deck}}</p>
{% endfor %}
{% for game in games2 %}
<p><a href="/game/{{ game.id }}">{{ game }}</a>  --  {{game.p2Deck}}</p>
{% endfor %}

<b><p>Propose Game</p></b>
<div class="proposal_div">
{{ userDrop.as_p }}
{% include "deck_drop.html" %}
<input style=float:left;width:300px name="Message" type="text" class="proposal-message"/>
<input class="propose-button" type="submit" value="Propose Game" />
</div>
<script>

function accept(a){
	var id = a.target.id;
	var url = a.target.href;
	var selector = ".proposal" + id + " > form > .deck_drop";
	var deckID = $(selector).val();
	url += "/" + deckID;
	a.target.href = url;
}


function propose(e){
	var message = $(".proposal-message").val();
	var recipient = $("#id_usersDrop").val();
	var deck = $(".proposal_div > form > .deck_drop").val();
	if( recipient == ""){
		alert("Please select a user to propose game to.");
	} else {
		var values = {};
		values['message'] = message;
		values['deck'] = deck;
		values['recipient'] = recipient;
		$.ajax({
			data: values,
			type: 'post',
			url:"/propose/",
			success: function(){
				window.location.reload();
			}
		});	
	}
}

$(document).ready(function(){
	$(".accept").bind("click", accept);
	$(".propose-button").bind("click", propose);
});

</script>

{% include "chat.html" %}
{% else %}
	<p>[<a href="/login/">login</a>]</p>
{% endif %}
{% endblock %}

templates/main_page.html
{% extends "base.html" %}
{% block title %}News{% endblock %}
{% block head %}News{% endblock %}
{% block style %}
<style type="text/css">
#chat{
	width:85%;
	height:300px;
}
</style>
{% endblock %}
{% block content %}

{% if user.username %}




{% else %}
	<p>[<a href="/login/">login</a>]</p>
{% endif %}
{% endblock %}

templates/news.html
{% extends "base.html" %}
{% block title %}News{% endblock %}
{% block head %}News{% endblock %}
{% block style %}
<style type="text/css">
</style>
{% endblock %}
{% block content %}

{% if user.username %}
<a href=https://bitbucket.org/thenmal/lotr-online/issues>Open Issues</a>
{% else %}
	<p>[<a href="/login/">login</a>]</p>
{% endif %}
{% endblock %}

templates/user_page.html
<html>
	<head>
		<title>Django Bookmarks - User: {{ username }}</title>
	</head>
	<body>
		<h1>Bookmarks for {{ username }}</h1>
			{% if bookmarks %}
			<ul>
				{% for bookmark in bookmarks %}
				<li><a href="{{ bookmark.link.url }}">
					{{ bookmark.title }}</a></li>
				{% endfor %}
			</ul>
		{% else %}
		<p>No bookmarks found.</p>
		{% endif %}
	</body>
</html>